twisted/treq

- treq/test/test_treq_integration.py
Treq uses httpbin to test! Unfortunately, it changed how it handled a list of headers, and removed the space (as it should).
This fixes it.
> HTTPBin changed underneath treq

- requirements-dev.txt
- setup.py
We use requests.cookies.merge_cookies, which is only present in requests >= 2.1.0
> Fix requests dependency

- README.rst
The previous badge url linked to the dreid/treq old repository (not present on travis).
> Update README.rst travis badge and add pypi badge.

- requirements-dev.txt
- setup.py
#101 removed Twisted < 13.2.0 from the test build matrix - since it's no longer tested, we should then probably require that Twisted be >= 13.2.0 in the setup and requirements file.
> Bump twisted requirement up to 13.2.0

- .gitignore
- requirements-dev.txt
- setup.py
Also remove the version requirement on pyOpenSSL because service_identity
requires 0.12 anyway.
> Dedup dependencies

- requirements-dev.txt
- tox.ini
Newer versions do not support Python 2.6 which is breaking our tests: https://travis-ci.org/twisted/treq/jobs/70658274 e.g. in #96
> Pin mock to 1.0.1

- docs/howto.rst
- treq/api.py
- treq/test/test_api.py
There was a small race condition between @glyph and me.  This PR should fix that. :)
- it links the Agent docs which should be useful if someone is reading about it
- show a more practical example instead of an opaque function
- simplify the agent logic.  kwargs isn’t used further down so no need to remove agent from it
- add a doc string to the test
- some whitespace fixes
> Small fixup to recent agent changes

- treq/test/test_testing.py
- treq/testing.py
>Previously, only completely synchronous responses would pass through successfully. Now, any sync or async response will pass through without issue. This adds a `flush` method to RequestTraversalAgent and StubTreq to pass data through.
Oh, and I fixed a bug in an unrelated test.
> Allow async responses from RequestTraversalAgent

- treq/api.py
- treq/client.py
- treq/test/test_client.py
Unfortunately, not all servers and server software respect [RFC2616 section 10.3](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3). Some of them will send a redirect after a POST request, which raises an exception. 
This PR adds a keyword argument (`browser_like_redirects `) to `HTTPClient.request` to
allow selecting the `BrowserLikeRedirectAgent` instead of the regular
`RedirectAgent `
> Allow selection of RedirectAgent

- treq/__init__.py
`pkg_resources` keeps causing weird packaging issues, like [this](https://travis-ci.org/rackerlabs/mimic/jobs/156439316).  This change is functionally identical, but uses `twisted.python.modules` instead.
> use twisted, instead of pkg_resources, for version

- treq/content.py
- treq/test/test_content.py
Default text encoding for JSON is UTF-8 not ISO-8859-1 like regular text content, as per [IETF RFC4627](http://www.ietf.org/rfc/rfc4627.txt).
> Python 3: Decode JSON text as UTF-8 by default

- .travis.yml
- setup.py
- tox.ini
Pursuant to #120, upgrade the build matrix to Twisted 16.0+.
> Update build matrix to Twisted 16.x

- setup.py
- treq/client.py
- treq/test/test_client.py
If passed a unicode URI normalize it to ASCII in an IDN-aware way.
Prereq: #137
> Handle Internationalized Domain Names

- treq/test/test_testing.py
- treq/testing.py
> Encode header values in treq.testing.HasHeaders

- docs/index.rst
I missed updating the docs in #138. I'd be happy to add an example if anyone knows of a site like httpbin.org but with an IDN.
> Update docs for IDN support

- setup.cfg
- setup.py
- tox.ini
* Remove setup.cfg ``[metadata]`` section, which didn't match setup.py and [is deprecated anyway](https://wheel.readthedocs.io/en/latest/#defining-conditional-dependencies).
* Instead of depending on Twisted's various TLS dependencies directly, depend on Twisted[tls] which has been present since at least Twisted 16.0.0 (but retain a higher PyOpenSSL dep for Python 3, since ``Twisted[tls]`` requires a lesser version).
> Dependency cleanup

- tox.ini
According to the readme PyPI page[1] the readme_renderer distribution should be used instead.
[1]: https://pypi.python.org/pypi/readme
> Tox: Use readme_renderer instead of readme

- setup.py
This is a (presumably temporary) work-around for #164.
It will fix the build failures until the underlying problem with the implementation is addressed.
> Avoid Twisted 17.1.0

- MANIFEST.in
- README.rst
- requirements-dev.txt
- setup.py
Fixes #165 
In passing, I also removed the README directions for installing pyOpenSSL since it is already declared as a dependency and any `pip install treq` will bring it and its dependencies in.
> Switch to a "dev" extra for dev requirements

- docs/examples/basic_post.py
- docs/examples/download_file.py
- docs/examples/query_params.py
- docs/examples/response_history.py
- docs/examples/using_cookies.py
As pointed out in #151 the basic_post.py example didn't work in Python 3. This also updates the others to be source compatible.
> Update examples to work on Python 3

- .readthedocs.yml
- .rtd-requirements.txt
- MANIFEST.in
The merge of #166 broke [the RTD build](https://readthedocs.org/projects/treq/builds/5040690/), where using a requirements file (so that the install goes through pip instead of setuptools) was the only way I could get it to correctly install pyasn1 (`python setup.py install` [got confused by pyasn1-modules](https://readthedocs.org/projects/treq/builds/4906698/)).
> Fix the ReadTheDocs build

- docs/examples/iresource.py
- docs/examples/testing_seq.py
- docs/index.rst
- docs/testing.rst
- src/treq/test/test_testing.py
- src/treq/testing.py
This PR adds some narrative documentation of the `treq.testing` module based on my reading of the code and [experience](https://github.com/twm/yarrharr/commit/f2a853fb9f8e349e0c948d838d03697551cc0f36) [using](https://github.com/twm/yarrharr/commit/3fa6779ef67bc5125c8985aec0440eb39b9d5949) it.  I'd appreciate review and feedback, particularly from the original authors/reviews with respect to their intent and any limitations I haven't noted.
> Narrative docs for treq.testing

- .travis.yml
- setup.py
- tox.ini
As discussed in https://github.com/twisted/treq/pull/175#issuecomment-289319932 and the following comments, treq should depend on a version of Twisted that _itself_ depends on a Python 3 compatible version of pyOpenSSL.  This allows treq to completely eliminate its pyOpenSSL dependency and with it tox environments that test incompatible combinations of pyOpenSSL and Twisted.  These incompatible combinations prevent otherwise working PRs from building, like https://github.com/twisted/treq/pull/177.
@glyph points out that these tox environments' intent might have been to exercise treq-Twisted-pyOpenSSL combinations that occur when a user relies on a system-provided Twisted.  If that's the case, this PR might also need a documentation change that explains that installing from PyPI is the …
> Eliminate pyOpenSSL dependency

- setup.py
- src/treq/testing.py
A non-WIP version of https://github.com/twisted/treq/pull/175.  Thanks, @tomprince !
> Testing custom endpoint

- .gitignore
- src/treq/content.py
- src/treq/test/test_content.py
> Fix text_content with non-ASCII headers under Python 3

- docs/index.rst
As #178 shows, it's easy to miss updating the docs when changing setup.py.  Lacking an easy way to automate this, I think it's best to just delegate communication of this this information to PyPI.
> Remove mention of dep versions from the docs

- src/treq/_version.py
This commit changes the name 'Treq' in _version.py to 'treq'. This makes the Version capitalization consistent with the caps throughout the package, and makes it possible to use `__version__.local()` to generate a local version number with incremental.
> Use lower-case package name in Version

- docs/testing.rst
Fix a few errors which make it through review of #173.
* Add a missing underscore to create a link.
* Make some class names absolute so that they get linked.
* Don't reference `StubTreq.flush()` which doesn't exist; instead reference `RequestTraversalAgent.flush()` which does.
> Fix links in the narrative testing docs

- src/treq/test/local_httpbin/parent.py
This is useful when e.g. running the test suite without installing treq first, specifying PYTHONPATH will work after the change.
> Inherit parent's environment variables to child

- setup.py
`httpbin>=0.6.0`  breakes on pypy with `undefined symbol: _Py_ZeroStruct` error,
which is being raised by the regex dependency
> Pin the httpbin version in setup.py

- src/treq/content.py
- src/treq/test/test_content.py
Per RFC-4627 content with type application/json must be encoded
in Unicode. So it is worth to return UTF-8 as an encoding charset
in such cases as a default.
> Assume UTF-8 charset when application/json is set

- .travis.yml
- setup.py
- tox2travis.py
Should fix [this](https://travis-ci.org/jameshilliard/treq/builds/294363299) test failure.
> Python 3.3 requires enum34 to be installed

- tox.ini
In tox.ini:
* Set VIRTUALENV_NO_DOWNLOAD=1 so that virtualenv doesn't attempt to
download the latest pip, setuptools, and wheel. Instead it uses the
bundled wheels without hitting the network.
* Set PIP_DISABLE_VERSION_CHECK=1 so that pip doesn't hit the network
to see if it's up to date.
This is a port of https://github.com/twisted/klein/pull/191
> Disable pip version check, virtualenv download

- docs/examples/testing_seq.py
- src/treq/test/test_testing.py
- src/treq/testing.py
Provide a default async failure reporter which, when not overridden, logs a match failure so that Trial knows to fail the test.
I also added some notes to the docs which relate to #205. Hopefully folks won't stub their toes too badly before the next Twisted release.
Closes #190
> Add default async failure reporter to RequestSequence

- src/treq/response.py
- src/treq/test/test_response.py
Teach `treq.response._Response` to display itself like this:
```
>>> import treq
>>> r = treq.get('https://httpbin.org/bytes/1024')
>>> r.result
<treq.response._Response 200 'application/octet-stream' 1,024 bytes>
```
Closes #189.
> repr for augmented responses

- docs/howto.rst
This PR fixes a small issue in the documentation.
To be able to use a custom Agent, you need to instantiate `treq.client.HTTPClient` instead of passing it  on `treq.get()` kwargs
> Fix agent customization sample code

- src/treq/content.py
- src/treq/response.py
- src/treq/test/test_response.py
Sometimes you need to be able to load a `Decimal` from a remote endpoint.
> allow customization of loading json; pass params to loads()

- .travis.yml
- setup.py
- src/treq/test/test_multipart.py
- tox.ini
- tox2travis.py
"CONTENT-LENGTH" is an undocumented new requirement in Python 3.7. I've asked upstream to clarify that - https://bugs.python.org/issue34226. There's a similar fix for twisted at https://github.com/twisted/twisted/commit/aa601a92de6a1e95f6525433f2e23a74040a93aa
> Add Python 3.7 support and enable testing

- docs/examples/download_file.py
Prior to this change, treq would buffer the entire file in memory, and Python's memory usage would rise to match the entire file size.
> examples: stream downloaded file without buffering

- src/treq/api.py
Add API documentation for the "agent" keyword parameter to the request()
method.
> api: document "agent" parameter to request()

- src/treq/testing.py
The header value is passed to [IRequest.setHeader()](https://twistedmatrix.com/documents/current/api/twisted.web.iweb.IRequest.html#setHeader) which accepts strings, not lists of strings.
> Correct RequestSequence response tuple type docs

- src/treq/test/test_testing.py
The tests are currently failing on `master` for the `-latest` environments.
> Fix to accommodate Twisted's new URL validity checking

- .travis.yml
- tox.ini
Resolve this warning:
pypi-readme run-test: commands[0] | python setup.py check -r -s
running check
warning: Check: This command has been deprecated. Use `twine check` instead: https://packaging.python.org/guides/making-a-pypi-friendly-readme#validating-restructuredtext-markup
The project's long description is valid RST.
Also rename the "pypi-readme" Tox environment to "twine" to match [the one with the same function in Twisted's tox.ini](https://github.com/twisted/twisted/blob/2f16887c734e8a29ab82e8cb5bc93b479c744597/tox.ini#L136).
> setup.py check → twine check

- MANIFEST.in
Fixes this failure when running `tox -e docs && tox -e check-manifest`:
```
check-manifest run-test: commands[0] | check-manifest
lists of files in version control and sdist do not match!
missing from VCS:
docs/html
docs/html/.buildinfo
docs/html/.doctrees
docs/html/.doctrees/api.doctree
docs/html/.doctrees/environment.pickle
docs/html/.doctrees/howto.doctree
docs/html/.doctrees/index.doctree
docs/html/.doctrees/testing.doctree
docs/html/_downloads
docs/html/_downloads/21c3ef61009ab7283a17cb445c9921a8
docs/html/_downloads/21c3ef61009ab7283a17cb445c9921a8/basic_auth.py
docs/html/_downloads/3e64a2ec014262f001c671ca9238e211
docs/html/_downloads/3e64a2ec014262f001c671ca9238e211/query_params.py
docs/html/_downloads/613abf8bde51fe26d8d237fd009196d0 …
```
> Exclude built docs from source package

- src/treq/client.py
When Tox is installed under Python 3 its default interpreter is used to
run flake8. Python 3 doesn't define the `file` variable. While this is
part of a branch that only runs on Python 2 it's easiest to just switch
to the equivalent name `open`.
Fixes this failure:
flake8 run-test: commands[0] | flake8 src/treq/
src/treq/client.py:344:33: F821 undefined name 'file'
> Fix flake8 failure on Python 3

- treq/api.py
- treq/test/test_api.py
Rather than encouraging people to mess around with `agent=` in the treq signature.
This is a continuation of @cwaldbieser's work from #109 .
> Mention, and emphasize, `HTTPClient` in the documentation

- .travis.yml
- tox.ini
Twisted trunk no longer supports Python 2.7.
> Remove Python 2.7 Twisted trunk builds

- src/treq/client.py
- src/treq/multipart.py
- src/treq/test/test_multipart.py
- src/treq/test/test_testing.py
https://github.com/twisted/treq/issues/288
> Use six instead of twisted.python.compat

- changelog.d/278.doc.rst
- docs/examples/basic_post.py
- docs/examples/json_post.py
- docs/howto.rst
- docs/index.rst
I converted the POST on the homepage to a regular form submission and added a fuller example of JSON to the use cases page. I'll revisit the documentation homepage again in another PR.
Fixes #278.
> Improve JSON documentation

- changelog.d/295.bugfix.rst
- setup.py
This fixes a regression introduced in #290.
https://github.com/benjaminp/six/blob/c0be8815d13df45b6ae471c4c436cce8c192245d/CHANGES#L30-L31
Fixes #295.
> Update metadata to require six >= 1.13

- changelog.d/294.removal.rst
- src/treq/client.py
- src/treq/test/test_client.py
Closes #294.
This is built on #297. I'll rebase it once that's in.
> Deprecate ignoring non-string headers

- .github/workflows/ci.yaml
- changelog.d/305.feature.rst
- setup.py
- tox.ini
Add Python 3.9 to the test matrix and package metadata.
Closes #305.
> Support Python 3.9

- .github/workflows/ci.yaml
- changelog.d/318.removal.rst
- docs/testing.rst
- setup.py
- src/treq/_agentspy.py
- src/treq/auth.py
- src/treq/client.py
- src/treq/content.py
- src/treq/multipart.py
- src/treq/response.py
- src/treq/test/local_httpbin/child.py
- src/treq/test/local_httpbin/parent.py
- src/treq/test/local_httpbin/shared.py
- src/treq/test/local_httpbin/test/test_child.py
- src/treq/test/test_api.py
- src/treq/test/test_client.py
- src/treq/test/test_content.py
- src/treq/test/test_multipart.py
- src/treq/test/test_response.py
- src/treq/test/test_testing.py
- src/treq/test/util.py
- src/treq/testing.py
- tox.ini
- Update package metadata to require Python 3.6 or later.
- Drop compatibility dependencies `six` and `mock`.
Closes #318.
> Drop support for Python 2.7 and 3.5

- .gitignore
- .readthedocs.yml
- CONTRIBUTING.rst
- changelog.d/296.doc.rst
- setup.py
- tox.ini
- Use Python 3.7 instead of 2.7 to build the documentation
- Move the Sphinx dependency to the ``docs`` extra
I've also enabled PR builds in the ReadTheDocs configuration, so the build status should be reported here.
Closes #296.
> Fix ReadTheDocs build

- changelog.d/329.feature.rst
- pyproject.toml
- tox.ini
This moves the build-time dependency on incremental to a declarativefile. See [1] for background.
[1]: https://twistedmatrix.com/trac/ticket/9457
> Add PEP 517 / PEP 518 metadata

- changelog.d/327.bugfix.rst
- docs/api.rst
- docs/testing.rst
- src/treq/test/test_testing.py
- src/treq/testing.py
This PR contains my proposed fix for #327. For details about the issue and this fix, see said issue.
**tl;dr of original issue:** Previously, a resource wrapped by `treq.testing.StubTreq` could not properly use `request.getSession()`, as it would always create a new `twisted.web.server.Session` instead of returning the same one. This is because `treq.testing.StubTreq` always create a new instance of `twisted.web.server.Site` for each request. As sessions are stored within a `Site` instance, this meant that upon completion of a request, the original session was lost. This PR solves this issue by moving the `twisted.web.server.Site` instance to an attribute of the agent. Additionally, the new `treq.testing.StubTreq.cleanSessions()` method provides a simple way of expiring the sessions in …
> treq.testing.StubTreq: fix persisting twisted.web.server.Session objects between requests

- docs/howto.rst
- docs/index.rst
- src/treq/client.py
- src/treq/multipart.py
Remove byte decoding for return value of `quote_plus()`. Not needed after we dropped Python 2 support.
> Cleanup: remove bytes decoding for quoted result
